Parameters:
  mystack: 
    Type: String
    Default: tedep22

Resources:
  Gits3buck:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: bucktag
          Value: !Ref mystack


          
